version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2
  test:
    jobs:
      - test
————————————————
版权声明：本文为CSDN博主「qinzhao168」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/qq_21816375/article/details/79140795