apiVersion: v1
kind: Service 
metadata:
  name: center0 
  labels:
    app: center0 
spec:
  selector:
    app: center0
  clusterIP: 10.96.200.203
  ports:
  - port: 8010 
    targetPort: 8010
    name: center0-p1
  - port: 18010 
    targetPort: 18010 
    name: center0-p2 
