apiVersion: v1
kind: ReplicationController
metadata:
  name: center0
spec:
  replicas: 1
  selector:
    app: center0 
  template:
    metadata:
      labels:
        app: center0
    spec:
      containers:
      - name: center0 
        image: 192.168.50.206:5000/ubuntuforgolang:v4
        imagePullPolicy: Always 
        ports:
        - 
          containerPort: 8010
          containerPort: 18010
        command: ["/home/workspace/regnet-tools/run.sh"]
        args: ["master","center","0"]
        volumeMounts:
        - name: nfs-storage
          mountPath: /home/workspace
      volumes:
        - name: nfs-storage
          nfs:
            server: 192.168.50.206
            path: /home/nfs
