apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway0 
spec:
  replicas: 1
  selector:
    app: gateway0
  template:
    metadata:
      labels:
        app: gateway0 
    spec:
      containers:
      - name: gateway0 
        image: 192.168.50.206:5000/ubuntuforgolang:v4
        imagePullPolicy: IfNotPresent 
        command: ["/home/workspace/regnet-tools/run.sh"]
        args: ["master","gateway","0"]
        ports:
        -
          containerPort: 8070
          containerPort: 18070
        volumeMounts:
        - name: nfs-storage
          mountPath: /home/workspace
      volumes:
        - name: nfs-storage
          nfs:
            server: 192.168.50.206
            path: /home/nfs
