apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch 
    spec:
      nodeSelector:
        app: vm-node-238 
      containers:
      - name: elasticsearch 
        image: 192.168.50.206:5000/elasticsearch:6.4.2
        imagePullPolicy: IfNotPresent
        env:
        -
          name: "discovery.type"
          value: "single-node"
        ports:
        - 
          containerPort: 9200
          containerPort: 9300
