apiVersion: v1
kind: Service 
metadata:
  name: kibana 
  labels:
    app: kibana 
spec:
  selector:
    app: kibana 
  type: NodePort
  ports:
  - port: 5601 
    targetPort: 5601 
    nodePort: 31561 
    name: kibana-p1 
