apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana 
spec:
  replicas: 1
  selector:
    app: kibana 
  template:
    metadata:
      labels:
        app: kibana
    spec:
      nodeSelector:
        app: vm-node-238 
      containers:
      - name: kibana 
        image: 192.168.50.206:5000/kibana:6.4.2
        imagePullPolicy: IfNotPresent 
        ports:
        - 
          containerPort: 5601 
