apiVersion: v1
kind: Pod
metadata:
  name: miner1 
  labels:
    app: miner1 
spec:
  containers:
  - name: miner1 
    image: 192.168.50.206:5000/ubuntuforgolang:v1
    imagePullPolicy: IfNotPresent
    ports:
    -
      containerPort: 8050
      containerPort: 18050
    command: ["/home/workspace/regnet-tools/run.sh"]
    args: ["master","miner","1"]
    volumeMounts:
    - name: nfs-storage
      mountPath: /home/workspace
  volumes:
    - name: nfs-storage
      nfs:
        server: 192.168.50.206
        path: /home/nfs
