apiVersion: v1
kind: Pod
metadata:
  name: miner0 
  labels:
    app: miner0 
spec:
  containers:
  - name: miner0 
    image: 192.168.50.206:5000/ubuntuforgolang:v1
    imagePullPolicy: Always 
    ports:
    -
      containerPort: 8050
      containerPort: 18050
    command: ["/home/workspace/regnet-tools/run.sh"]
    args: ["master","miner","0"]
    volumeMounts:
    - name: nfs-storage
      mountPath: /home/workspace
  volumes:
    - name: nfs-storage
      nfs:
        server: 192.168.50.206
        path: /home/nfs
