apiVersion: v1
kind: Pod
metadata:
  name: user0 
  labels:
    app: user0 
spec:
  containers:
  - name: user0 
    image: 192.168.50.206:5000/ubuntuforgolang:v1
    imagePullPolicy: IfNotPresent
    command: ["/home/workspace/regnet-tools/run.sh"]
    args: ["master","user","0"]
    ports:
    -
      containerPort: 18060
    volumeMounts:
    - name: nfs-storage
      mountPath: /home/workspace
  volumes:
    - name: nfs-storage
      nfs:
        server: 192.168.50.206
        path: /home/nfs
