apiVersion: v1
kind: Service 
metadata:
  name: gateway0 
  labels:
    app: gateway0
spec:
  selector:
    app: gateway0
  clusterIP: 10.96.200.213
  ports:
  - port: 8010 
    targetPort: 8010
    name: gateway0-p1
  - port: 18010 
    targetPort: 18010 
    name: gateway0-p2 
