apiVersion: v1
kind: Service 
metadata:
  name: redis 
  labels:
    app: redis 
spec:
  selector:
    app: redis 
  clusterIP: 10.96.200.202
  ports:
  - port: 6379 
    targetPort: 6379
    name: redis-port 
