apiVersion: v1
kind: ReplicationController
metadata:
  name: redis 
spec:
  replicas: 1
  selector:
    app: redis 
  template:
    metadata:
      labels:
        app: redis 
    spec:
      containers:
      - name: redis 
        image: 192.168.50.206:5000/redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - 
          containerPort: 6379 
