apiVersion: v1
kind: ReplicationController
metadata:
  name: verifier0 
spec:
  replicas: 1
  selector:
    app: verifier0 
  template:
    metadata:
      labels:
        app: verifier0 
    spec:
      nodeSelector:
        app: vm-node-236 
      containers:
      - name: verifier0 
        image: 192.168.50.206:5000/ubuntuforgolang:v4
        imagePullPolicy: IfNotPresent 
        command: ["/home/workspace/regnet-tools/run.sh"]
        args: ["master","verifier","0"]
        volumeMounts:
        - name: nfs-storage
          mountPath: /home/workspace
      volumes:
        - name: nfs-storage
          nfs:
            server: 192.168.50.206
            path: /home/nfs
